name: Bash Syntax Check

on:
  push:
    branches: [ main, new ]
  pull_request:
    branches: [ main, new ]

jobs:
  check-syntax:
    name: Check Bash Syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
            echo "Running ShellCheck on all Bash scripts..."
            find . -type f -name "*.sh" -exec shellcheck {} +
             echo "ShellCheck completed successfully!"
      - name: Ensure file_list.txt Exists
        run: |
          if [ ! -f file_list.txt ]; then
            touch file_list.txt
            echo "Created file_list.txt"
          fi

      - name: Add Error-Free Scripts to file_list.txt
        run: |
          echo "Adding valid scripts to file_list.txt..."
          for script in $(find . -name "*.sh"); do
            if ! grep -q "$script" file_list.txt; then
              echo "$script" >> file_list.txt
              echo "✅ Added: $script"
            fi
          done

      - name: Upload Updated File List
        uses: actions/upload-artifact@v4
        with:
          name: updated-file-list
          path: file_list.txt
      - name: Commit & Push Updated file_list.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add file_list.txt
          git commit -m "Auto-update file_list.txt"
          git push origin main || echo "No changes to commit."
